### ISSUE TITLE
`inline-var` produces incorrect output if no semicolons are used

### ISSUE THREAD

**Issue by DanielBrookRoberge** [magnars/js2-refactor.el#101]
The `inline-var` operation leaves the `const`, `let` or `var` keyword in place if the file being edited does not use semicolons.

Example before:
```js
const fn = () => {
  const count = 10
  if (count > 5) {
    console.log('True')
  }
}
```

After:
```js
const fn = () => {
  const  if (10 > 5) {
    console.log('True')
  }
}
```

Expected:
```js
const fn = () => {
  if (10 > 5) {
    console.log('True')
  }
}
```

**Comment by Fuco1** [comment]
I was about to file the same issue, except I couldn't get to the bottom of it. 

I think that the function `js2r--was-single-var` could use the ast to decide what to do instead of just doing a text check, otherwise I don't see any good way to decide what to do.

**Comment by NicolasPetton** [comment]
@Fuco1 It's true that the proper fix would be to use the AST. However that will be a large refactoring, so in the meantime I'll push a simpler fix that uses a more robust regexp.

**Comment by Fuco1** [comment]
I can confirm this works for me, thanks! :heart:
