### ISSUE TITLE
Does js2-refactor hard-require yasnippet ?

### ISSUE THREAD

**Issue by re-mx** [magnars/js2-refactor.el#108]
Hello , first sorry for my poor English...

I currently **DO NOT** want to install `yasnippet` for some reason,
But it seems that every time I install `js2-refactor`, `yasnippet` will be automatically installed.

Is `js2-refactor` hard dependent on yasnippet?

Thanks.

**Comment by NicolasPetton** [comment]
MX Reimu <notifications@github.com> writes:

> Is `js2-refactor` hard dependent on yasnippet?

Yes, some refactorings use yasnippet, sorry.

**Comment by re-mx** [comment]
Well……

I will see if there is any way to hack it.

Thank you for your reply
