### ISSUE TITLE
Feature request: add-require

### ISSUE THREAD

**Issue by Wilfred** [magnars/js2-refactor.el#40]
Another feature I'd love to see: the ability to require a variable at point. From

```
foo.bar()
```

to

```
var foo = require('foo');

foo.bar();
```

we could take the 'foo' from the symbol at point, or scan the enclosing directory, or scan the node_modules directory.

**Comment by NicolasPetton** [comment]
I'm closing this issue, but if you still think it would be a good idea to implement it, we can can keep discussing it and maybe create a separate package for it?

**Comment by Wilfred** [comment]
Thanks, no worries. I'm not writing a lot of JS at the moment. If I do write more in future, I'll definitely send a patch for discussion.

(Thanks for mentioning amd-mode, that's new to me and definitely useful.)
