### ISSUE TITLE
js2r-extract-var weird behavior inside else if

### ISSUE THREAD

**Issue by Ryckes** [magnars/js2-refactor.el#43]
In a buffer like the following, being + the mark and * the point (that is, everything inside the parentheses is selected):

        else if(+38 in game.keysDown*) { // Up

After `M-x js2r-extract-var` this is the result:

        else var name = 38 in game.keysDown;
        if(name) { // Up

I don't know if it would be easy to go up to the first if statement of the "if - else if" from there.

**Comment by NicolasPetton** [comment]
The issue should have been fixed.with b89358e
