### ISSUE TITLE
Add js2r-declare-var

### ISSUE THREAD

**Issue by jacksonrayhamilton** [magnars/js2-refactor.el#47]
Hi there. I've written a function for adding declarations to multi-line `var` statements. I developed it in the `js2-mode` repo and [submitted a PR for it](https://github.com/mooz/js2-mode/pull/219) there, but now I see that this might be a better home for it.

If you're interested, I could port it to this project. It is pretty well-tested in the `js2-mode` repo. Maybe I can do some regular expression replacements to convert the tests into your format.

**Comment by jacksonrayhamilton** [comment]
I will probably be submitting a PR within the next few days if you don't say "no."

Already got it nearly integrated [here](https://github.com/jacksonrayhamilton/js2-refactor.el/commit/7286e75955c5e2bfca8cb874cbf9e2e79afaf27a).

**Comment by magnars** [comment]
Looks nice. :)

**Comment by jacksonrayhamilton** [comment]
Ultimately I've decided against submitting a PR for this functionality. I think it is far too complicated, and I no longer code in a style that would benefit from this change.
