### ISSUE TITLE
Inline var doesn't work well with `const`, `let`

### ISSUE THREAD

**Issue by brianloveswords** [magnars/js2-refactor.el#49]
Hi! I'm working on some ES6 code and just noticed that inline var'ing leaves behind a `onst ;` or `et ;` when inlining a variable declared with either `const` or `let`. Example:

```js
// before
const test = function() {
  const thing = 'Thing';
  console.log(thing);
};

// after
const test = function() onst ;
  console.log('Thing');
};
```

A similar thing happens with `let`.

I'm happy to try to work on a patch though I'm somewhere between total notice and reckless amateur when it comes to elisp and it'd be helpful if you pointed me in the general direction of the relevant code :)

**Comment by magnars** [comment]
Does js2-mode parse ES6 code properly? That would be the place to start in any case. :) If it works all right, the next part is finding the definition for `js2r-inline-var` with `C-h f`, and then start combing through the code for the places it just assumes that variables are defined using "var". :)
