### ISSUE TITLE
js2-minor-mode - keymap not defined

### ISSUE THREAD

**Issue by Nupf** [magnars/js2-refactor.el#53]
Is there a reason the keys are added exclusively to the js2-mode-map? 
If js2-refactor also works when only using the js2-minor-mode, it would make sense to set up keybindings there as well.

**Comment by NicolasPetton** [comment]
Nupf writes:

> Is there a reason the keys are added exclusively to the js2-mode-map? 
> If js2-refactor also works when only using the js2-minor-mode, it
> would make sense to set up keybindings there as well.

My plan is to make js2r a minor-mode. It should fix your problem.

**Comment by NicolasPetton** [comment]
Should be fixed now that #54 has been merged.
