### ISSUE TITLE
Need package `yasnippet-20130218', but only 0.9.0.1 is available

### ISSUE THREAD

**Issue by 2manyprojects2littletime** [magnars/js2-refactor.el#56]
I'm fairly new to emacs, so this could be a simple fix and I'm not yet sophisticated enough as a user to figure it out.  I presume the workaround would be to dl and compile from sources?  Any insight would be helpful.

**Comment by paulbdavis** [comment]
I ran into this today, it is because of the version number you are getting from MELPA Stable vs this package expecting a version number like the one in MELPA

**Comment by NicolasPetton** [comment]
Does commit 6ede40 fix the issue?
