### ISSUE TITLE
Which functions are not dependent on js2-mode?

### ISSUE THREAD

**Issue by louy2** [magnars/js2-refactor.el#57]
Is it possible to enable this mode in other major mode to enjoy them?

**Comment by louy2** [comment]
My guess:

 * `ef` is `extract-function`: Extracts the marked expressions out into a new named function.
 * `eo` is `expand-object`: Converts a one line object literal to multiline.
 * `co` is `contract-object`: Converts a multiline object literal to one line.
 * `eu` is `expand-function`: Converts a one line function to multiline (expecting semicolons as statement delimiters).
 * `cu` is `contract-function`: Converts a multiline function to one line (expecting semicolons as statement delimiters).
 * `ea` is `expand-array`: Converts a one line array to multiline.
 * `ca` is `contract-array`: Converts a multiline array to one line.
 * `wi` is `wrap-buffer-in-iife`: Wraps the entire buffer in an immediately invoked function expression
 * `ig` is `inject-global-in-iife`: Creates a shortcut for a marked global by injecting it in the wrapping immediately invoked function expression
 * `ag` is `add-to-globals-annotation`: Creates a `/*global */` annotation if it is missing, and adds the var at point to it.
 * `ev` is `extract-var`: Takes a marked expression and replaces it with a var.
 * `3i` is `ternary-to-if`: Converts ternary operator to if-statement.
 * `sv` is `split-var-declaration`: Splits a `var` with multiple vars declared, into several `var` statements.
 * `ss` is `split-string`: Splits a `string`.
 * `lt` is `log-this`: Adds a console.log() statement for what is at point (or region).
 * `dt` is `debug-this`: Adds a debug() statement for what is at point (or region).
 * `k` is `kill`: Kills to the end of the line, but does not cross semantic boundaries.

**Comment by magnars** [comment]
js2-mode comes with its own JavaScript parser, and js2-refactor relies heavily on the AST it builds.
