### ISSUE TITLE
An error occurred while installing js2-refactor

### ISSUE THREAD

**Issue by kostrse** [magnars/js2-refactor.el#59]
--> installing javascript:js2-refactor... [4/9]
An error occurred while installing js2-refactor

```
(error: (cl-assertion-failed (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))))
```

Windows 10
GNU Emacs 24.5.1 (i686-pc-mingw32)

**Comment by magnars** [comment]
This error must be in the package manager. Try opening an issue with Melpa or Marmalade if that's where you're getting it.
