### ISSUE TITLE
How to actually use C-m as a binding

### ISSUE THREAD

**Issue by favetelinguis** [magnars/js2-refactor.el#61]
Since Emacs belive C-m is the RET key im not able to bind C-c C-m , Emacs is just telling me C-c RET is undefined.

Is there something im missing when using the following line of code to actually make this binding?
```
(js2r-add-keybindings-with-prefix "C-c C-m")
```

**Comment by magnars** [comment]
Write `C-c RET`

**Comment by favetelinguis** [comment]
Aa ok, another point is C-S-down and C-S-up, im using my Super key for xmonad. Are there any alternatie bindings for these?

**Comment by magnars** [comment]
Yep, just bind the commands to something else. :)
fre. 12. feb. 2016 kl. 09.42 skrev Henrik Larsson <notifications@github.com

**Comment by favetelinguis** [comment]
thanks
