### ISSUE TITLE
ES6 Constructs

### ISSUE THREAD

**Issue by bolivier** [magnars/js2-refactor.el#75]
Right now a lot of the refactors assume that I want to refactor with ES5 syntax. 

Most of my codebases are using ES6 at this point, so I often have to change vars and functions.  It would be nice to have a setting that would convert `var`s to `let`s or `const`s and `function()`s to `() =>`s. 

I'd be more than happy to implement something like this myself if there's interest in the features.

**Comment by NicolasPetton** [comment]
Do you want refactorings to convert things like `var` to `let`, or do you want an option that would make `js2-refactor` use es6 constructs?

**Comment by jakoblind** [comment]
I would want something like this also. @NicolasPetton from my perspective I would want to be able to convert for example a `var` to a `const`. I don't want an option. 

If the maintainer decides to add these type of feature, I can help contributing. I have already pushed a PR that got rejected that converted `require` to `imports` and vice versa. I am not sure that should have been rejected.

**Comment by jakoblind** [comment]
Hi, I have created a new package with ES6 features which is an extension to `js2-refactor` called [js2r-es6](https://github.com/jakoblind/js2r-es6). I put them in this separate package because maintainers decided it doesn't belong here. 

I intend to put more ES6 related features in this package

**Comment by NicolasPetton** [comment]
Thanks for the link! 

I'm not at all against ES6 features in `js2r`, but I just talked about module loading.
Please keep sending PRs!

**Comment by NicolasPetton** [comment]
@jakoblind maybe it was a mistake to reject your PR. It's never too late to discuss it again though.

**Comment by jakoblind** [comment]
I am not sure what is the correct thing regarding that PR. Maybe it's fine to not include it.

**Comment by jakoblind** [comment]
@bolivier I have read the code and realized we had some undocumented features! You can already do `function () => {}` to `() => {}` with `ta`. Just wanted to let you know :) I have updated the readme file.

**Comment by bolivier** [comment]
I was actually thinking of something that would make js2-refactor use es6 constructs.  For instance, I would like extract-var to use `const` or `let` instead of `var`.

**Comment by NicolasPetton** [comment]
@bolivier commit https://github.com/magnars/js2-refactor.el/commit/823416959b9e5dbb206bcad4376b4f2cf4ffa238 adds a defcustom to prefer let over var.
