### ISSUE TITLE
Package not found when doing package-install

### ISSUE THREAD

**Issue by rohan-varma** [magnars/js2-refactor.el#93]
I get the following error with `M-x package-install js2-refactor`: 
```
Contacting host: melpa.milkbox.net:80 package-install-from-archive: 

http://melpa.milkbox.net/packages/yasnippet-20170226.1638.tar: Not found

```

Any advice? Thanks.

**Comment by NicolasPetton** [comment]
Rohan Varma <notifications@github.com> writes:

> I get the following error with `M-x package-install js2-refactor`:

Try again, MELPA might have updated its packages just when you tried to
install them.

**Comment by NicolasPetton** [comment]
I just tried with a clean Emacs, and it works fine, so I'm closing this issue. If you still have problems installing js2-refactor, feel free to reopen it.
